---
# file: roles/desktop/tasks/main.yml

- name: install_repositories_additional_keys
  apt_key: url='{{ item }}' state=present
  with_items:
    - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key             # insync

- name: install_repositories_additional
  apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib
    - ppa:webupd8team/java
    - ppa:webupd8team/sublime-text-3
    - ppa:numix/ppa
    - ppa:atareao/telegram

- name: accept_java_license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: install_packages
  apt: name={{ item }} state=present
  with_flattened:
    - packages_misc
    - packages_devel
    - packages_xdeps
    - packages_xapps

- name: add_user_to_docker_group
  user: name={{ default_user }} groups=docker append=yes state=present
