---
# file: roles/desktop/tasks/main.yml

- name: install_repositories_additional_keys
  apt_key: url='{{ item }}' state=present
  with_items:
    - https://dl.google.com/linux/linux_signing_key.pub                               # google

- name: install_repositories_additional
  apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - deb http://dl.google.com/linux/chrome/deb/ stable main
    - deb http://dl.google.com/linux/talkplugin/deb/ stable main
    - ppa:webupd8team/java
    - ppa:webupd8team/sublime-text-3
    - ppa:numix/ppa
    - ppa:atareao/telegram

- name: disable_package_repositories_install
  copy: content="" dest='{{ item }}' owner=root group=root mode=0644
  with_items:
    - /etc/default/google-chrome
    - /etc/default/google-talkplugin

- name: accept_java_license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install_packages
  apt: name={{ item }} state=present
  with_flattened:
    - "{{ packages_misc }}"
    - "{{ packages_devel }}"
    - "{{ packages_xdeps }}"
    - "{{ packages_xapps }}"

- name: remove_packages
  apt: name={{ item }} state=absent purge=yes
  with_flattened:
    - "{{ packages_remove }}"

- name: add_user_to_docker_group
  user: name={{ default_user }} groups=docker append=yes state=present
