---
# file: roles/desktop/vars/main.yml

packages_misc:
  - autojump
  - aria2
  - ddclient
  - asciinema

packages_devel:
  - ruby-dev
  - rbenv
  - ruby-build
  - python-dev
  - python-pip
  - python-virtualenv
  - oracle-java8-installer
  - vagrant

packages_xdeps:
  - numix-icon-theme-circle
  - numix-gtk-theme

packages_xapps:
  - thunderbird
  - gimp
  - rawtherapee
  - calibre
  - xclip
  - shutter
  - virtualbox
  - insync
  - sublime-text-installer
  - telegram

packages_remove:
  - evolution
