---
# file: roles/mydesktop/tasks/main.yml

- name: install_repositories_additional
  apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - ppa:graphics-drivers/ppa

- name: install_packages_drivers
  apt: name={{ item }} state=present
  with_flattened:
    - packages_drivers

- name: create_xorg_config_directory
  file: path=/etc/X11/xorg.conf.d state=directory owner=root group=root mode=0755

- name: install_config_nvidia
  copy: src=20-nvidia.conf dest=/etc/X11/xorg.conf.d/20-nvidia.conf owner=root group=root mode=0644

- name: install_config_clutter_paint
  lineinfile: dest=/etc/environment regexp='^CLUTTER_PAINT=' line='CLUTTER_PAINT=disable-clipped-redraws:disable-culling'

- name: install_config_clutter_vblank
  lineinfile: dest=/etc/environment regexp='^CLUTTER_VBLANK=' line='CLUTTER_VBLANK=True'
